import Link from "next/link";
import { adminConfigured, isAdmin } from "@/lib/auth";
import { getLeads, getLeadStatus, statuses } from "@/lib/leads";
import { login, logout, changeStatus } from "@/app/actions";
import { money, products, finishes } from "@/lib/quotation";
export const dynamic = "force-dynamic";
export const metadata = { title: "Lead management | Ayezza", robots: { index: false, follow: false } };
export default async function Admin({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const params = await searchParams;
  if (!(await isAdmin())) return <main className="admin-login"><Link className="eyebrow" href="/">← AYEZZA ALUMINUM</Link><h1>Welcome back.</h1><p>Manage your quotation requests and project leads.</p>{!adminConfigured() ? <p className="notice">Set ADMIN_PASSWORD to at least 16 characters in .env.local to enable team access.</p> : <form action={login}><label>Team password<input name="password" type="password" autoComplete="current-password" required maxLength={200}/></label>{params.error && <p role="alert" className="form-error">Incorrect password. Please try again.</p>}<button className="button primary">Sign in</button></form>}</main>;
  const leads = await Promise.all((await getLeads()).map(async lead => ({ ...lead, status: await getLeadStatus(lead) })));
  return <main className="admin-shell"><div className="admin-header"><div><Link href="/" className="eyebrow">AYEZZA / TEAM WORKSPACE</Link><h1>Project leads</h1></div><form action={logout}><button className="button secondary">Sign out</button></form></div><div className="stat-grid"><div><small>Total inquiries</small><strong>{leads.length}</strong></div><div><small>New leads</small><strong>{leads.filter(l => l.status === "New").length}</strong></div><div><small>Estimated pipeline · sample rates</small><strong>{money(leads.filter(l => l.status !== "Lost" && l.status !== "Won").reduce((sum, l) => sum + l.total, 0))}</strong></div></div>{!leads.length && <div className="empty-state"><h2>Your next project starts here.</h2><p>Submitted website quotations will appear here with customer details and specifications.</p><Link className="button primary" href="/#quotation">View quotation form</Link></div>}<div className="lead-list">{leads.map(lead => <article className="lead-card" key={lead.id}><div className="lead-heading"><div><span className="eyebrow">{new Date(lead.createdAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })} · {lead.id.slice(0, 8)}</span><h2>{lead.name}</h2><p>{lead.location}</p></div><strong>{money(lead.total)}</strong></div><div className="lead-contact"><a href={`mailto:${lead.email}`}>{lead.email}</a><a href={`tel:${lead.phone.replace(/[^+\d]/g, "")}`}>{lead.phone}</a></div><ul>{lead.items.map((item, i) => <li key={i}>{item.quantity} × {products.find(p => p.id === item.product)?.name} · {item.width} × {item.height} m · {finishes.find(f => f.id === item.finish)?.name}</li>)}</ul>{lead.notes && <p className="lead-notes">{lead.notes}</p>}<form action={changeStatus} className="status-form"><input type="hidden" name="id" value={lead.id}/><label>Status<select name="status" defaultValue={lead.status}>{statuses.map(status => <option key={status}>{status}</option>)}</select></label><button className="button secondary">Save status</button></form></article>)}</div></main>;
}
