import { ArrowDown, ArrowRight, ArrowUpRight, Layers3, MoveUpRight, Ruler, ShieldCheck, Sparkles } from "lucide-react";
import { Architecture, WindowDrawing } from "@/components/architecture";
import QuoteBuilder from "@/components/quote-builder";
import { products } from "@/lib/quotation";
export default function Home() {
  return <>
    <div className="announcement">Thoughtfully crafted aluminum. Made for your everyday.</div>
    <header className="site-header"><a className="brand" href="/" aria-label="Ayezza Aluminum home"><span className="brand-symbol">a<span>.</span></span><span>AYEZZA<small>ALUMINUM & GLASS</small></span></a><nav aria-label="Main navigation"><a href="#systems">Our systems</a><a href="#difference">Why Ayezza</a><a href="#process">How it works</a></nav><a href="#quotation" className="button nav-cta">Get a quotation <ArrowUpRight size={17}/></a></header>
    <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="green-dot"/> BETTER FRAMES. BETTER SPACES.</div><h1>Open up to<br/>a beautifully<br/><em>built space.</em></h1><p>Custom aluminum windows, doors, and glass solutions that bring your vision into view.</p><div className="hero-actions"><a className="button primary" href="#quotation">Build your quotation <ArrowUpRight size={18}/></a><a className="text-link" href="#systems">Explore our systems <ArrowDown size={15}/></a></div><div className="hero-note"><span className="note-icon"><Ruler size={19}/></span><span>Made to measure.<br/><strong>Designed around you.</strong></span><span className="note-line"/><span>For homes.<br/><strong>For businesses. For you.</strong></span></div></div><div className="hero-visual"><Architecture/><div className="image-top-label"><span className="green-dot"/> THE ART OF EVERYDAY LIVING</div><div className="image-caption"><div><small>THE POSSIBILITIES, REFRAMED</small><strong>Less frame. More living.</strong></div><a href="#systems" aria-label="Explore aluminum systems"><MoveUpRight size={25}/></a></div><div className="vertical-caption">ARCHITECTURAL CONCEPT / AYEZZA ALUMINUM</div></div></section>
    <div className="benefit-strip"><span><Ruler size={21}/> Custom-fit precision</span><span><ShieldCheck size={21}/> Built for everyday durability</span><span><Sparkles size={21}/> Clean, timeless finishes</span><span><Layers3 size={21}/> Residential & commercial</span></div>
    <section className="section systems" id="systems"><div className="section-heading"><div><p className="eyebrow">FIND YOUR PERFECT FIT</p><h2>A system for every space.</h2></div><a href="#quotation" className="text-link">Create your estimate <ArrowUpRight size={17}/></a></div><div className="product-grid">{products.map((product, i) => <a className="product-card" href="#quotation" key={product.id}><div className={`product-art art-${i}`}><span className="product-category">{product.category}</span><WindowDrawing type={product.id}/><span className="product-arrow"><ArrowUpRight size={18}/></span></div><div className="product-description"><span>0{i + 1}</span><div><h3>{product.name}</h3><p>{product.detail}</p></div></div></a>)}</div></section>
    <section className="difference section" id="difference"><div className="difference-visual"><WindowDrawing type="casement-window" dark/><div className="dimension dimension-top">MADE TO MEASURE</div><span className="material-chip"><span/> Aluminum, thoughtfully detailed.</span></div><div className="difference-copy"><p className="eyebrow">MORE THAN A FRAME</p><h2>The details make<br/>the difference.</h2><p>A good space starts with the right choices. We bring together considered design, practical materials, and a fit that feels just right.</p><div className="difference-points"><div><span>01</span><div><h3>Your dimensions. Our starting point.</h3><p>Custom specifications for the way you live and work.</p></div></div><div><span>02</span><div><h3>Simple lines. Lasting character.</h3><p>Versatile aluminum finishes that complement your space.</p></div></div><div><span>03</span><div><h3>Clarity at every step.</h3><p>Start with an estimate, then refine the details with our team.</p></div></div></div></div></section>
    <section className="section process" id="process"><div className="section-heading"><div><p className="eyebrow">FROM AN IDEA TO YOUR EVERYDAY</p><h2>A little planning. A whole new view.</h2></div></div><div className="process-grid">{[{ title: "Make it yours", text: "Choose your system, finish, and measurements using our quotation builder." }, { title: "Let’s talk details", text: "Send your project details. Our team will review your requirements with you." }, { title: "Bring it to life", text: "Confirm the site measurements, final quotation, and installation schedule." }].map((step, i) => <div key={step.title}><span className="process-number">0{i + 1}</span><ArrowRight size={19}/><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>
    <QuoteBuilder/>
    <section className="closing"><p className="eyebrow">A BETTER VIEW STARTS HERE</p><h2>Let’s make room for your vision.</h2><a className="button light" href="#quotation">Start your project <ArrowUpRight size={18}/></a></section>
    </main><footer><a className="brand" href="/">AYEZZA<small>ALUMINUM & GLASS</small></a><p>Thoughtfully framed. Beautifully yours.</p><div><a href="/privacy">Privacy</a><a href="/admin">Team login</a><span>© {new Date().getFullYear()} Ayezza Aluminum</span></div></footer>
  </>;
}
